### ISSUE TITLE
Max, Min, and Close icons aren't visible in Windows (and possibly Linux?)

### ISSUE THREAD

**Issue by hojberg** [unisonweb/ucm-desktop#14]
Currently the window buttons to maximize, minimize, and close aren't shown on Windows (and likely also aren't shown on Linux).

**Comment by DejanMilicic** [comment]
This is fixed in latest version on Windows

**Comment by hojberg** [comment]
While the application toolbars aren't looking great on windows and linux, I'll track that as a different issue and close this one.
