### ISSUE TITLE
Panel resizing is not working on Windows version

### ISSUE THREAD

**Issue by DejanMilicic** [unisonweb/ucm-desktop#19]
![image](https://github.com/user-attachments/assets/216d83d7-eb47-431b-9050-5a2142180a0d)

**Comment by hojberg** [comment]
I mean this edge 
![CleanShot 2024-12-12 at 13 59 02@2x](https://github.com/user-attachments/assets/bcc3553b-a5e0-4c3d-9cd6-f269aea1a933)

**Comment by DejanMilicic** [comment]
No, that is not working either

**Comment by DejanMilicic** [comment]
Fixed in latest build!
