### ISSUE TITLE
"Error" on Windows startup.

### ISSUE THREAD

**Issue by aryairani** [unisonweb/ucm-desktop#8]
![image](https://github.com/user-attachments/assets/078b5769-90ce-4129-b425-1c6b03715144)

This is on a new codebase but `ucm` has already been started up previously. I used the .msi installer.

ucm 0.5.28

Let me know how I can help!

**Comment by hojberg** [comment]
Just added some more error details to this message, but its likely that it can't connect to UCM.

Side note: also looks like there's some issue with the window controls (min, max, close).

**Comment by hojberg** [comment]
@aryairani another possible reason might be if UCM is started _after_ the desktop app is started. The app handles that case poorly right now. See https://github.com/unisonweb/ucm-desktop/issues/10

**Comment by DejanMilicic** [comment]
I am running into same problem

![image](https://github.com/user-attachments/assets/6d81b4b0-dca0-4a4b-bc74-f1ca60b944a1)

on the other hand, I have UCM running as described in instructions

![image](https://github.com/user-attachments/assets/6e662029-ebb7-4c31-99ff-4dafe18deea0)

accessing `http://127.0.0.1:4444/asdf` manually in the browser indeed gives 404, while `http://127.0.0.1:4444/asdf/api` is fully functional

**Comment by DejanMilicic** [comment]
> @DejanMilicic did you by chance start the desktop app _before_ starting the cli? (It doesn't automatically recover if its started in the wrong order atm)

I just verified it one more time - I started ucm, and after that I started ucm-desktop

**Comment by hojberg** [comment]
@DejanMilicic thanks, thats super helpfup

**Comment by hojberg** [comment]
Close this out, use the instructions above to run the app on Windows.
I'm tracking the lack of the min, max, close buttons here: https://github.com/unisonweb/ucm-desktop/issues/14
